version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.1
    - 4.15.2
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.1
    - 4.15.2
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.21.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
    - 26.0.22
  - dependency-name: ts-jest
    versions:
    - 26.5.0
    - 26.5.1
    - 26.5.2
    - 26.5.4
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.2.2
