name: Example workflow for Codecov
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
   
#     - name: Setup Python  
#       uses: actions/setup-python@master

#     - name: Generate coverage report
#       run: |
#         pip install pytest
#         pip install pytest-cov
#         pytest --cov=./ --cov-report=xml

    - name: Upload coverage to Codecov  
      uses: .
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        flags: unittest
        name: codecov-1
        #badstuff: morebadstuff
